// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: workflow_completion.proto

package workflowcompletionpb

import (
	v1 "go.temporal.io/api/failure/v1"
	_ "go.temporal.io/sdk/sdkcore/internal/ffi/corepb/commonpb"
	workflowcommandspb "go.temporal.io/sdk/sdkcore/internal/ffi/corepb/workflowcommandspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

/// Result of a single workflow activation, reported from lang to core
type WFActivationCompletion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The task queue the workflow activation you are completing originated from
	TaskQueue string `protobuf:"bytes,1,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	// The run id from the workflow activation you are completing
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Types that are assignable to Status:
	//	*WFActivationCompletion_Successful
	//	*WFActivationCompletion_Failed
	Status isWFActivationCompletion_Status `protobuf_oneof:"status"`
}

func (x *WFActivationCompletion) Reset() {
	*x = WFActivationCompletion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_completion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WFActivationCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WFActivationCompletion) ProtoMessage() {}

func (x *WFActivationCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_completion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WFActivationCompletion.ProtoReflect.Descriptor instead.
func (*WFActivationCompletion) Descriptor() ([]byte, []int) {
	return file_workflow_completion_proto_rawDescGZIP(), []int{0}
}

func (x *WFActivationCompletion) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *WFActivationCompletion) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (m *WFActivationCompletion) GetStatus() isWFActivationCompletion_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (x *WFActivationCompletion) GetSuccessful() *Success {
	if x, ok := x.GetStatus().(*WFActivationCompletion_Successful); ok {
		return x.Successful
	}
	return nil
}

func (x *WFActivationCompletion) GetFailed() *Failure {
	if x, ok := x.GetStatus().(*WFActivationCompletion_Failed); ok {
		return x.Failed
	}
	return nil
}

type isWFActivationCompletion_Status interface {
	isWFActivationCompletion_Status()
}

type WFActivationCompletion_Successful struct {
	Successful *Success `protobuf:"bytes,3,opt,name=successful,proto3,oneof"`
}

type WFActivationCompletion_Failed struct {
	Failed *Failure `protobuf:"bytes,4,opt,name=failed,proto3,oneof"`
}

func (*WFActivationCompletion_Successful) isWFActivationCompletion_Status() {}

func (*WFActivationCompletion_Failed) isWFActivationCompletion_Status() {}

/// Successful workflow activation with a list of commands generated by the workflow execution
type Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of commands to send back to the temporal server
	Commands []*workflowcommandspb.WorkflowCommand `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
}

func (x *Success) Reset() {
	*x = Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_completion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_completion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_workflow_completion_proto_rawDescGZIP(), []int{1}
}

func (x *Success) GetCommands() []*workflowcommandspb.WorkflowCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

/// Failure to activate or execute a workflow
type Failure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Failure *v1.Failure `protobuf:"bytes,1,opt,name=failure,proto3" json:"failure,omitempty"`
}

func (x *Failure) Reset() {
	*x = Failure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_completion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_completion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_workflow_completion_proto_rawDescGZIP(), []int{2}
}

func (x *Failure) GetFailure() *v1.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

var File_workflow_completion_proto protoreflect.FileDescriptor

var file_workflow_completion_proto_rawDesc = []byte{
	0x0a, 0x19, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x64, 0x6b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x25, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe0, 0x01, 0x0a, 0x16, 0x57, 0x46, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x12, 0x15, 0x0a, 0x06, 0x72, 0x75, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x75, 0x6e, 0x49, 0x64, 0x12, 0x46, 0x0a, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x66, 0x75, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x64, 0x6b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x12,
	0x3e, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x64, 0x6b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c,
	0x6f, 0x77, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x42,
	0x08, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x51, 0x0a, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x46, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x64, 0x6b,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x22, 0x45, 0x0a, 0x07,
	0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f,
	0x72, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x07, 0x66, 0x61, 0x69, 0x6c,
	0x75, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workflow_completion_proto_rawDescOnce sync.Once
	file_workflow_completion_proto_rawDescData = file_workflow_completion_proto_rawDesc
)

func file_workflow_completion_proto_rawDescGZIP() []byte {
	file_workflow_completion_proto_rawDescOnce.Do(func() {
		file_workflow_completion_proto_rawDescData = protoimpl.X.CompressGZIP(file_workflow_completion_proto_rawDescData)
	})
	return file_workflow_completion_proto_rawDescData
}

var file_workflow_completion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workflow_completion_proto_goTypes = []interface{}{
	(*WFActivationCompletion)(nil),             // 0: coresdk.workflow_completion.WFActivationCompletion
	(*Success)(nil),                            // 1: coresdk.workflow_completion.Success
	(*Failure)(nil),                            // 2: coresdk.workflow_completion.Failure
	(*workflowcommandspb.WorkflowCommand)(nil), // 3: coresdk.workflow_commands.WorkflowCommand
	(*v1.Failure)(nil),                         // 4: temporal.api.failure.v1.Failure
}
var file_workflow_completion_proto_depIdxs = []int32{
	1, // 0: coresdk.workflow_completion.WFActivationCompletion.successful:type_name -> coresdk.workflow_completion.Success
	2, // 1: coresdk.workflow_completion.WFActivationCompletion.failed:type_name -> coresdk.workflow_completion.Failure
	3, // 2: coresdk.workflow_completion.Success.commands:type_name -> coresdk.workflow_commands.WorkflowCommand
	4, // 3: coresdk.workflow_completion.Failure.failure:type_name -> temporal.api.failure.v1.Failure
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_workflow_completion_proto_init() }
func file_workflow_completion_proto_init() {
	if File_workflow_completion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workflow_completion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WFActivationCompletion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_completion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_completion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Failure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_workflow_completion_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*WFActivationCompletion_Successful)(nil),
		(*WFActivationCompletion_Failed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workflow_completion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_completion_proto_goTypes,
		DependencyIndexes: file_workflow_completion_proto_depIdxs,
		MessageInfos:      file_workflow_completion_proto_msgTypes,
	}.Build()
	File_workflow_completion_proto = out.File
	file_workflow_completion_proto_rawDesc = nil
	file_workflow_completion_proto_goTypes = nil
	file_workflow_completion_proto_depIdxs = nil
}
